version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: no
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ../certs:/etc/nginx/certs:ro
      #- vhostd:/etc/nginx/vhost.d
      - /usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: no
    volumes:
      - ../certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes:
      - ../certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  www:
    image: nginx
    restart: no
    expose:
      - "80"
    volumes:
      - ../www:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=gilbarsan.com,www.gilbarsan.com
      - LETSENCRYPT_HOST=gilbarsan.com,www.gilbarsan.com
      - LETSENCRYPT_EMAIL=gilbarsan@gilbarsan.com
